vcpkg_check_linkage(ONLY_STATIC_LIBRARY)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO menghuijinxi/SkiaUI
    REF bc81617ae7ca660adcd2d4cd5b85a3bdf84687a7
    SHA512 f8f721ef3c04d2c69538523c4696fb1decaf1a6b5cd4ad6eb0dfa4d4c6d005a1722d488d7cd5d2862964a6b8734c020ce361a876f6d0c9d194e8d9abe1029ca9
    HEAD_REF master
)

set(SKIAUI_DEMO OFF)
if("demo" IN_LIST FEATURES)
    set(SKIAUI_DEMO ON)
endif()

set(SKIAUI_WIN32 OFF)
if("win32" IN_LIST FEATURES OR "win32-dx12" IN_LIST FEATURES OR SKIAUI_DEMO)
    set(SKIAUI_WIN32 ON)
endif()

set(SKIAUI_WIN32_DX12 OFF)
if("win32-dx12" IN_LIST FEATURES OR SKIAUI_DEMO)
    set(SKIAUI_WIN32_DX12 ON)
endif()

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DSKIAUI_BUILD_DEMOS=OFF
        -DSKIAUI_BUILD_TESTS=OFF
        -DSKIAUI_BUILD_SKIA_UI_DESK=${SKIAUI_DEMO}
        -DSKIAUI_INSTALL_SKIA_UI_DESK=${SKIAUI_DEMO}
        -DSKIAUI_BUILD_WIN32=${SKIAUI_WIN32}
        -DSKIAUI_INSTALL_WIN32=${SKIAUI_WIN32}
        -DSKIAUI_BUILD_WIN32_DX12=${SKIAUI_WIN32_DX12}
        -DSKIAUI_INSTALL_WIN32_DX12=${SKIAUI_WIN32_DX12}
        -DSKIATEST_USE_SKIA_D3D=ON
)

vcpkg_cmake_install()
vcpkg_cmake_config_fixup()

file(REMOVE_RECURSE
    "${CURRENT_PACKAGES_DIR}/debug/include"
    "${CURRENT_PACKAGES_DIR}/debug/share"
)

file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
file(WRITE "${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright"
    "SkiaUI currently does not declare a license.\n"
)
